### ISSUE TITLE
[cetic/zabbix] NodePort not being set properly

### ISSUE THREAD

**Issue by niklasweimann** [cetic/helm-zabbix#39]
**Describe the bug**
If you want to use zabbix with an external zabbix agent you need to have the port 10051 exposed to external hosts. To get this you need to use the NodePort option as described in (https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport). The helm chart does not provide a way to set the nodePort option. So Kubernetes will pick a random port which is not useful in case of an fully automated deployment of zabbix agents.

**Version of Helm and Kubernetes**:
not important in this case.

**What happened**:
The NodePort is not being set on the Service.

**What you expected to happen**:
The NodePort is set properly with the value configured in the helm-chart.

**How to reproduce it** (as minimally and precisely as possible):
Use the following config for zabbix-server. The nodePort value will not be set correctly

``` yaml
# **Zabbix server** configurations
zabbixserver:
  service:
    # -- Type of service in Kubernetes cluster
    type: ClusterIP
    # -- Cluster IP for Zabbix server
    clusterIP: 
    # -- Port of service in Kubernetes cluster
    port: 31051
```
